### ISSUE TITLE
doesn't work with latest ACF Pro 6.0.2

### ISSUE THREAD

**Issue by andsat** [kevinruscoe/acf-star-rating-field#50]
error in console:

`jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading '0') TypeError: Cannot read properties of undefined (reading '0')
    at initialiseField (http://wraptorclaw.local.test/wp-content/plugins/acf-star-rating-field/js/input.js:10:38)
    at HTMLDivElement.<anonymous> (http://wraptorclaw.local.test/wp-content/plugins/acf-star-rating-field/js/input.js:75:4)
    at Function.each (http://wraptorclaw.local.test/wp-includes/js/jquery/jquery.min.js:2:3003)
    at s.fn.init.each (http://wraptorclaw.local.test/wp-includes/js/jquery/jquery.min.js:2:1481)
    at http://wraptorclaw.local.test/wp-content/plugins/acf-star-rating-field/js/input.js:74:11
    at http://wraptorclaw.local.test/wp-content/plugins/advanced-custom-fields-pro/assets/build/js/acf-input.min.js:1:2262
    at o (http://wraptorclaw.local.test/wp-content/plugins/advanced-custom-fields-pro/assets/build/js/acf.min.js:1:1417)
    at Object.doAction (http://wraptorclaw.local.test/wp-content/plugins/advanced-custom-fields-pro/assets/build/js/acf.min.js:1:587)
    at n.doAction (http://wraptorclaw.local.test/wp-content/plugins/advanced-custom-fields-pro/assets/build/js/acf.min.js:1:18166)
    at HTMLDocument.<anonymous> (http://wraptorclaw.local.test/wp-content/plugins/advanced-custom-fields-pro/assets/build/js/acf.min.js:1:27130) undefined`

**Comment by dhunink** [comment]
I'm experiencing the same issue. Looks like something goes wrong with the SVG rendering as well. Is this plugin still maintained?

**Comment by MGParisi** [comment]
Doesn't work with ACF non-pro either, and seems to be now crashing ACF admin interface.

I started looking at it, and there is a function render_field which creates a <script> tag with the initialization of that field in it.  For some reason, this doesn't seem to be getting added.

**Comment by MGParisi** [comment]
https://github.com/kevinruscoe/acf-star-rating-field/blob/3166fd5dd35c2efa9580ec01d433832e7d9b1fbb/StarRatingField.php#L102

**Comment by MGParisi** [comment]
Also, SVG's work for me.  That is incorrect.  Only the SVG's from Font-Awesome are not working (according to the ticket)

**Comment by MGParisi** [comment]
Maybe a full fix?

This fixes the admin interfaces from crashing for ACF6.
https://github.com/MGParisi/acf-star-rating-field

I'm not sure if there is more.  I accept donations.

**Comment by kevinruscoe** [comment]
@MGParisi Hey, I'll take a look at this over the weekend and hopefully get it fixed.

**Comment by kevinruscoe** [comment]
I'm sorry, but I can't replicate the issues. 

I've just installed:

- WP 6.1
- ACF
- this plugin (from the master branch).
 
I made a simple star field and created a minimal theme

```
<?php 

wp_head();

while(have_posts()) {
    
    the_post();

    the_title();

    print get_field('star');

}

wp_footer();
```

And all 3 return types (number, list and FA list) work.

Can you guys provide more context, please?

**Comment by MGParisi** [comment]
@kevinruscoe 
Check out my fork, it resolves the issues.

**Comment by MGParisi** [comment]
@jarrod-collective 
Check out my fork, it resolves the issues.
